# docker-compose.yml

version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
  redis:
    image: redis
    ports:
      - "6379:6379"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
